server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
  application:
    name: account-rabbit-producer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    consul:
      discovery:
        register: true
        service-name: account-rabbit-producer
      host: localhost
      port: 8500
