info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: my-account-service
    customer: 
      path: /customer/**
      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFOmanagement:  endpoint:    shutdown:      enabled: true